version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ubuntu
        versions:
          - ">=25"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
